Use searchable tokens for existing version check
pulumi/upgrade-provider pull request #282
Opened 2024-10-25 02:37 UTC by danielrbradley

Filtering via @me assumes that the user is always the same when creating issues. This might not be true if a user runs this tool locally. This also breaks when the author is an app such as github-actions.

As an alternative approach, GitHub will index for search any word within the issue body, even hidden within an HTML comment. We use base64 encoding to turn an upstream version such as "v5.72.1" into "djUuNzIuMQ==" which is a single word which is highly unlikely to appear in any other issue.

Similarly, we'll include the word "pulumiupgradeproviderissue" in the HTML comment to allow listing all upgrade issues easily via search.

Here's an example issue where I've manually added this hidden comment to test searching:
- https://github.com/pulumi/pulumi-aws/issues/4652

We'll leave the existing "@me" based search in as a fallback until we can be confident that these tokens will be present in relevant issues.

Resolves #280

2024-10-25 21:51 UTC, iwahbe requested changes
I'd like to avoid situations where external users can effect our tooling. Instead of messing around with base64 encoded magic strings (which can be arbitrarily added to issues), can we simply make the `--author` customizable?

Pulumi could specify `--author` as pulumi-bot, others could set app/github-bot, or whatever is appropriate for their org.

That seems like a much simpler solution and I'm struggling to think of the down side.

2024-10-30 10:29 UTC, danielrbradley commented
Notes from call:
- We might want to retry the upgrade nightly, so should always output the latest version to try to upgrade to.
- Add more explanation of the tooling & magic labels used for issues.

Rollout plan:
1. Add new magic string and github output.
2. Update CI mgmt to combine jobs via new output.
3. Wait 1 week.
4. Switch issue search to use magic string.

2024-10-30 10:46 UTC, iwahbe approved these changes

2024-10-30 10:46 UTC, iwahbe commented on upgrade/steps_helpers.go
> +		if _, err := f.WriteString(fmt.Sprintf("issue_created=%t\n", issueAlreadyExists)); err != nil {
After discussion, this needs to be the latest version we want to upgrade to (if the provider is not already on the latest version), regardless of issue creation.

2024-10-30 10:46 UTC, iwahbe commented on upgrade/steps_helpers.go
> +	hiddenBody := fmt.Sprintf("<!-- %s -->", pulumiupgradeproviderissue)
Lets add a comment (visible to people who look at the opened issue description) that explains why this comment exists.

2024-10-30 10:46 UTC, iwahbe commented on upgrade/steps_helpers.go
> +	// Search through existing "pulumiupgradeproviderissue" issues to see if we've already created one for this version.
```suggestion
	// Search through existing pulumiupgradeproviderissue issues to see if we've already created one for this version.
```

2024-10-30 10:46 UTC, iwahbe commented on upgrade/steps_helpers.go
> +	// Fall back to searching through the issues from the current user.
Let's add a TODO and an issue for removing this logic.

2024-10-30 10:49 UTC, ringods approved these changes

2024-10-31 08:19 UTC, merged